name: Run Test with Spack

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test LILI with Spack
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop
        buildcache: true
        color: true
        path: spack

    - name: Replace with GitHub CI spack.yaml
      run: |
        cp .github/spack.yaml ./spack.yaml
        cat ./spack.yaml

    - name: Setup Spack mirror
      run: spack -e . mirror set --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache

    - name: Concretize Spack environment
      run: spack -e . concretize

    - name: Install Spack packages
      run: spack -e . install --no-check-signature

    - name: Compile LILI
      shell: spack-bash {0}
      run: |
        spack env activate .
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    - name: Push packages and update index
      run: spack -e . buildcache push --base-image ubuntu:22.04 --update-index local-buildcache
      if: ${{ !cancelled() }}
