name: Test Connection to Runner Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

    - name: Tailscale status
      run: |
        tailscale status

    - name: Tailscale ping
      run: |
        tailscale ping -c 1 ${{ secrets.LILI_RUNNER_ADD }}

    - name: Verify connection
      run: |
        echo "Connection to runner server successful"
