name: Test Connection to Runner Server

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci

  test-connection:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Tailscale ping
      run: |
        tailscale ping -c 1 ${{ secrets.LILI_RUNNER_ADD }}

    - name: Verify connection
      run: |
        if [ $? -eq 0 ]; then
          echo "Connection to runner server successful"
        else
          echo "Connection to runner server failed"
          exit 1
        fi
